/**
 * cloudflared named-tunnel config that publishes ONLY the remote listener (OAuth + read-only MCP).
 * The local admin API / Web UI port (daemon.port) is never part of it.
 */

export const DEFAULT_TUNNEL_HOSTNAME = 'uc.nemut.ai';
export const DEFAULT_TUNNEL_NAME = 'unicontext';

export interface TunnelConfigInput {
  /** Public hostname, e.g. uc.nemut.ai (from remote.publicUrl when set). */
  hostname: string;
  /** Tunnel name or UUID (`cloudflared tunnel create <name>`). */
  tunnel: string;
  /** Path of the tunnel credentials JSON written by `cloudflared tunnel create`. */
  credentialsFile: string;
  /** remote.port */
  port: number;
}

export function hostnameFromPublicUrl(publicUrl: string | undefined): string | undefined {
  if (!publicUrl) return undefined;
  try {
    return new URL(publicUrl).hostname;
  } catch {
    return undefined;
  }
}

function yamlString(value: string): string {
  return /^[A-Za-z0-9._/:\\-]+$/.test(value) ? value : JSON.stringify(value);
}

export function tunnelConfigYaml(input: TunnelConfigInput): string {
  if (!/^[A-Za-z0-9.-]+$/.test(input.hostname))
    throw new Error(`invalid hostname: ${input.hostname}`);
  return [
    '# cloudflared config for UniContext (generated by `unicontext remote tunnel-config`).',
    '# Publishes only the read-only remote MCP listener; the local admin API and Web UI stay private.',
    `tunnel: ${yamlString(input.tunnel)}`,
    `credentials-file: ${yamlString(input.credentialsFile)}`,
    'ingress:',
    `  - hostname: ${input.hostname}`,
    `    service: http://127.0.0.1:${input.port}`,
    '    # no httpHostHeader: UniContext checks the public Host against remote.publicUrl',
    '  - service: http_status:404',
    '',
  ].join('\n');
}
