/*
 * Wire types come from the daemon package, type-only: nothing from @unicontext/* may reach the
 * browser bundle at runtime. Every file in src imports types through here.
 */
export type {
  AnnouncementReadResponse,
  OpenAnnouncementsReport,
  DownloadFilesResponse,
  AdditionResponse,
  AdditionsResponse,
  AdditionView,
  AdminContext,
  AnnouncementResponse,
  AnnouncementsResponse,
  AssignmentItem,
  AssignmentsResponse,
  ChangesContext,
  Citation,
  ClassItem,
  ConflictItem,
  ConflictsResponse,
  CorrectBody,
  CorrectResponse,
  CourseAssignmentItem,
  CourseContext,
  CourseFileItem,
  CourseRef,
  CourseSummary,
  CoursesResponse,
  DeadlineItem,
  DiscussionItem,
  GradeAttempt,
  GradeCourse,
  GradePeriodTotals,
  GradesResponse,
  IdentityBody,
  IdentityResponse,
  LectureBundle,
  Notification,
  NotificationsResponse,
  PaceCourseItem,
  PaceResponse,
  PaceSetBody,
  PaceSetResponse,
  PaceSlotView,
  ProposalView,
  ProposalsResponse,
  ResolvedValue,
  SearchResponse,
  SessionResponse,
  SettingsResponse,
  SourceInfo,
  SourceRefResponse,
  SourcesResponse,
  SyncResponse,
  TodayContext,
  WeekContext,
} from '@unicontext/daemon/api-types';

export type { IdentityLink } from '@unicontext/canonical-model';

export type {
  AnnouncementAttachment,
  AnnouncementDetail,
  AnnouncementItem,
  ChangeItem,
  MaterialItem,
  PreparationItem,
  TaskItem,
  ValueCandidate,
} from '@unicontext/context-engine';
