import { execFile } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { homedir as osHomedir } from 'node:os';
import path from 'node:path';

/*
 * Service install helpers for `unicontext service install|uninstall|status` (§34).
 *  - macOS:   launchd LaunchAgent plist
 *  - Windows: a wscript launcher (.vbs) in the user's Startup folder (NOT Task Scheduler)
 *  - Linux:   systemd --user unit
 * Rendering is pure so it can be tested on any OS; side effects go through ServiceDeps.
 */

export const SERVICE_LABEL = 'ai.nemut.unicontext';
export const SYSTEMD_UNIT = 'unicontextd.service';
export const WINDOWS_LAUNCHER = 'UniContext.vbs';

export interface ServiceSpec {
  /** Absolute path of the node executable. */
  nodePath: string;
  /** Absolute path of the daemon entry (apps/daemon/dist/bin.js). */
  daemonScript: string;
  /** Extra environment for the daemon (UNICONTEXT_DATA_DIR, ...). */
  env?: Record<string, string>;
  /** Directory the daemon logs to (stdout/stderr are redirected there where the manager supports it). */
  logDir: string;
}

export type ServicePlatform = 'darwin' | 'win32' | 'linux';

export interface ServiceStatus {
  platform: ServicePlatform;
  installed: boolean;
  /** Where the definition lives (plist, unit file or Startup launcher). */
  file: string;
  /** Manager-reported running state when it can be queried. */
  running: boolean | undefined;
  detail: string | undefined;
}

export interface ExecResult {
  code: number;
  stdout: string;
  stderr: string;
}

export interface ServiceDeps {
  exec(file: string, args: string[]): Promise<ExecResult>;
  homedir: string;
  env: Record<string, string | undefined>;
  uid: number | undefined;
}

export function defaultServiceDeps(): ServiceDeps {
  return {
    exec: (file, args) =>
      new Promise((resolve) => {
        execFile(file, args, { windowsHide: true }, (error, stdout, stderr) => {
          const code =
            error && typeof (error as NodeJS.ErrnoException & { code?: unknown }).code === 'number'
              ? (error as { code: number }).code
              : error
                ? 1
                : 0;
          resolve({ code, stdout: String(stdout), stderr: String(stderr) });
        });
      }),
    homedir: osHomedir(),
    env: process.env,
    uid: typeof process.getuid === 'function' ? process.getuid() : undefined,
  };
}

export function servicePlatform(platform: NodeJS.Platform = process.platform): ServicePlatform {
  if (platform === 'darwin' || platform === 'win32') return platform;
  return 'linux';
}

const xml = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function renderLaunchdPlist(spec: ServiceSpec): string {
  const env = Object.entries(spec.env ?? {})
    .map(([k, v]) => `    <key>${xml(k)}</key>\n    <string>${xml(v)}</string>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${SERVICE_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(spec.nodePath)}</string>
    <string>${xml(spec.daemonScript)}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>${xml(path.posix.join(spec.logDir, 'launchd.out.log'))}</string>
  <key>StandardErrorPath</key>
  <string>${xml(path.posix.join(spec.logDir, 'launchd.err.log'))}</string>
${env ? `  <key>EnvironmentVariables</key>\n  <dict>\n${env}\n  </dict>\n` : ''}</dict>
</plist>
`;
}

function systemdQuote(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/%/g, '%%')}"`;
}

export function renderSystemdUnit(spec: ServiceSpec): string {
  const env = Object.entries(spec.env ?? {})
    .map(([k, v]) => `Environment=${systemdQuote(`${k}=${v}`)}`)
    .join('\n');
  return `[Unit]
Description=UniContext daemon (local-first university context)
After=network-online.target

[Service]
Type=simple
ExecStart=${systemdQuote(spec.nodePath)} ${systemdQuote(spec.daemonScript)}
Restart=on-failure
RestartSec=10
${env ? `${env}\n` : ''}
[Install]
WantedBy=default.target
`;
}

const vbs = (s: string): string => s.replace(/"/g, '""');

/** Hidden-window launcher run by Windows at logon (Startup folder). */
export function renderWindowsLauncher(spec: ServiceSpec): string {
  const envLines = Object.entries(spec.env ?? {})
    .map(([k, v]) => `env("${vbs(k)}") = "${vbs(v)}"`)
    .join('\r\n');
  return [
    "' UniContext daemon launcher (generated by `unicontext service install`)",
    'Set sh = CreateObject("WScript.Shell")',
    'Set env = sh.Environment("Process")',
    ...(envLines ? [envLines] : []),
    `sh.Run """${vbs(spec.nodePath)}"" ""${vbs(spec.daemonScript)}""", 0, False`,
    '',
  ].join('\r\n');
}

export function serviceFile(
  platform: ServicePlatform,
  deps: Pick<ServiceDeps, 'homedir' | 'env'>,
): string {
  switch (platform) {
    case 'darwin':
      return path.posix.join(deps.homedir, 'Library', 'LaunchAgents', `${SERVICE_LABEL}.plist`);
    case 'win32': {
      const appData = deps.env.APPDATA ?? path.win32.join(deps.homedir, 'AppData', 'Roaming');
      return path.win32.join(
        appData,
        'Microsoft',
        'Windows',
        'Start Menu',
        'Programs',
        'Startup',
        WINDOWS_LAUNCHER,
      );
    }
    case 'linux': {
      const cfg = deps.env.XDG_CONFIG_HOME ?? path.posix.join(deps.homedir, '.config');
      return path.posix.join(cfg, 'systemd', 'user', SYSTEMD_UNIT);
    }
  }
}

export interface ServiceActionResult {
  platform: ServicePlatform;
  file: string;
  /** Human-readable steps performed or still required. */
  messages: string[];
}

export async function installService(
  spec: ServiceSpec,
  deps: ServiceDeps = defaultServiceDeps(),
  platform: ServicePlatform = servicePlatform(),
): Promise<ServiceActionResult> {
  const file = serviceFile(platform, deps);
  const messages: string[] = [];
  mkdirSync(path.dirname(file), { recursive: true });
  mkdirSync(spec.logDir, { recursive: true });
  switch (platform) {
    case 'darwin': {
      writeFileSync(file, renderLaunchdPlist(spec));
      messages.push(`LaunchAgent を作成しました: ${file}`);
      const domain = `gui/${deps.uid ?? 501}`;
      await deps.exec('launchctl', ['bootout', `${domain}/${SERVICE_LABEL}`]);
      const r = await deps.exec('launchctl', ['bootstrap', domain, file]);
      messages.push(
        r.code === 0
          ? 'launchd に登録して起動しました'
          : `launchctl bootstrap が失敗しました（${r.stderr.trim() || `exit ${r.code}`}）。次回ログイン時に起動します`,
      );
      break;
    }
    case 'win32': {
      writeFileSync(file, renderWindowsLauncher(spec));
      messages.push(`スタートアップにランチャーを作成しました: ${file}`);
      const r = await deps.exec('wscript.exe', [file]);
      messages.push(
        r.code === 0
          ? '今すぐ起動しました（次回ログインからも自動起動します）'
          : '次回ログインから自動起動します',
      );
      break;
    }
    case 'linux': {
      writeFileSync(file, renderSystemdUnit(spec));
      messages.push(`systemd ユーザーユニットを作成しました: ${file}`);
      await deps.exec('systemctl', ['--user', 'daemon-reload']);
      const r = await deps.exec('systemctl', ['--user', 'enable', '--now', SYSTEMD_UNIT]);
      messages.push(
        r.code === 0
          ? '有効化して起動しました'
          : `systemctl --user enable --now が失敗しました（${r.stderr.trim() || `exit ${r.code}`}）`,
      );
      break;
    }
  }
  return { platform, file, messages };
}

export async function uninstallService(
  deps: ServiceDeps = defaultServiceDeps(),
  platform: ServicePlatform = servicePlatform(),
): Promise<ServiceActionResult> {
  const file = serviceFile(platform, deps);
  const messages: string[] = [];
  switch (platform) {
    case 'darwin':
      await deps.exec('launchctl', ['bootout', `gui/${deps.uid ?? 501}/${SERVICE_LABEL}`]);
      break;
    case 'win32':
      // the running daemon is stopped with `unicontext daemon stop`; removing the launcher stops auto-start
      break;
    case 'linux':
      await deps.exec('systemctl', ['--user', 'disable', '--now', SYSTEMD_UNIT]);
      break;
  }
  if (existsSync(file)) {
    rmSync(file, { force: true });
    messages.push(`削除しました: ${file}`);
  } else messages.push('登録されていません');
  if (platform === 'linux') await deps.exec('systemctl', ['--user', 'daemon-reload']);
  if (platform === 'win32')
    messages.push('起動中のデーモンは unicontext daemon stop で止めてください');
  return { platform, file, messages };
}

export async function serviceStatus(
  deps: ServiceDeps = defaultServiceDeps(),
  platform: ServicePlatform = servicePlatform(),
): Promise<ServiceStatus> {
  const file = serviceFile(platform, deps);
  const installed = existsSync(file);
  if (!installed) return { platform, installed, file, running: undefined, detail: undefined };
  switch (platform) {
    case 'darwin': {
      const r = await deps.exec('launchctl', ['print', `gui/${deps.uid ?? 501}/${SERVICE_LABEL}`]);
      return {
        platform,
        installed,
        file,
        running: r.code === 0 && /state = running/.test(r.stdout),
        detail: r.code === 0 ? undefined : 'launchd に未登録',
      };
    }
    case 'linux': {
      const r = await deps.exec('systemctl', ['--user', 'is-active', SYSTEMD_UNIT]);
      const state = r.stdout.trim();
      return { platform, installed, file, running: state === 'active', detail: state || undefined };
    }
    case 'win32':
      return { platform, installed, file, running: undefined, detail: 'スタートアップに登録済み' };
  }
}
